---
abstract: 'Client for the Osgood Passive, Persistent Event Queue'
author:
  - "Cory 'G' Watson <gphat@cpan.org>"
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Osgood-Client
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0.41
  DateTime::Format::ISO8601: 0.06
  JSON::Any: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Moose: 0.26
  MooseX::AttributeHelpers: 0
  MooseX::Iterator: 0.07
  MooseX::Storage: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 2.0.6
